2025-04-01 15:45:07 - ISTLogger_model_logger - INFO - -----------------------------The file path is /home/nitinyadav/Music/testing/3_Satyapal_Srivastava-RE-New_1_.doc------------------------------------


2025-04-02 14:57:20 - ISTLogger_model_logger - INFO - -----------------------------The file path is /home/nitinyadav/Music/testing/K-12_Surveyor - Jose Monteiro.pdf------------------------------------


2025-04-02 14:57:20 - ISTLogger_model_logger - INFO - -----------------------------The file path is /home/nitinyadav/Music/testing/K-12_Surveyor - Jose Monteiro.pdf------------------------------------


2025-04-02 14:57:22 - ISTLogger_model_logger - INFO - -----------------------------The file path is /home/nitinyadav/Music/testing/K-12_Surveyor - Jose Monteiro.pdf------------------------------------


2025-04-02 14:57:22 - ISTLogger_model_logger - INFO - -----------------------------The file path is /home/nitinyadav/Music/testing/K-12_Surveyor - Jose Monteiro.pdf------------------------------------


2025-04-02 14:58:47 - ISTLogger_model_logger - INFO - The model retuned the status code of 200
2025-04-02 14:58:47 - ISTLogger_model_logger - INFO - The model retuned the status code of 200
2025-04-02 14:58:47 - ISTLogger_model_logger - ERROR - error in the complete model and the model returned empty data 

Traceback (most recent call last):
  File "/home/nitinyadav/Documents/cv_manager/resumeparser/general/get_data_model.py", line 24, in model_data
    start=text.index('{')
AttributeError: 'dict' object has no attribute 'index'
2025-04-02 14:58:47 - ISTLogger_model_logger - ERROR - error in the complete model and the model returned empty data 

Traceback (most recent call last):
  File "/home/nitinyadav/Documents/cv_manager/resumeparser/general/get_data_model.py", line 24, in model_data
    start=text.index('{')
AttributeError: 'dict' object has no attribute 'index'
2025-04-02 15:00:20 - ISTLogger_model_logger - INFO - The model retuned the status code of 200
2025-04-02 15:00:20 - ISTLogger_model_logger - INFO - The model retuned the status code of 200
2025-04-02 15:00:20 - ISTLogger_model_logger - ERROR - error in the complete model and the model returned empty data 

Traceback (most recent call last):
  File "/home/nitinyadav/Documents/cv_manager/resumeparser/general/get_data_model.py", line 24, in model_data
    start=text.index('{')
AttributeError: 'dict' object has no attribute 'index'
2025-04-02 15:00:20 - ISTLogger_model_logger - ERROR - error in the complete model and the model returned empty data 

Traceback (most recent call last):
  File "/home/nitinyadav/Documents/cv_manager/resumeparser/general/get_data_model.py", line 24, in model_data
    start=text.index('{')
AttributeError: 'dict' object has no attribute 'index'
